# NumPy

In [ ]:
x = [1, 2, 3]
x

[1, 2, 3]

In [ ]:
x * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
x * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
for i in x:
  print(i * 2)

2
4
6


In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [ ]:
x * 2

array([2, 4, 6])

In [ ]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [ ]:
%timeit my_arr2 = my_arr * 2

387 µs ± 36 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit my_list2 = [x * 2 for x in my_list]

31.5 ms ± 2.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Ndarray

In [ ]:
data = np.array([[1.2, 4, 5.5], [4.5, 6, 7]])
data

array([[1.2, 4. , 5.5],
       [4.5, 6. , 7. ]])

In [ ]:
data * 10

array([[12., 40., 55.],
       [45., 60., 70.]])

In [ ]:
data.ndim

2

In [ ]:
data.shape

(2, 3)

In [ ]:
dim1 = np.array([1, 2, 3])
dim2 = np.array([[1, 2, 3], [4, 5, 6]])
dim3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
dim1

array([1, 2, 3])

In [ ]:
dim2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
print(dim1.ndim)
print(dim2.ndim)
print(dim3.ndim)

1
2
3


In [ ]:
print(dim1.shape)
print(dim2.shape)
print(dim3.shape)

(3,)
(2, 3)
(2, 2, 3)


## Data Types

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [ ]:
dim3_float = dim3.astype(np.float64)
dim3_float

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

## Index y Slicing

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
data[3]

3

In [ ]:
data[2:6]

array([2, 3, 4, 5])

In [ ]:
data[2] = 50
data

array([ 0,  1, 50,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
data[:] = 100
data

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
dim2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
dim2[1]

array([4, 5, 6])

In [ ]:
dim2[1][1]

5

In [ ]:
dim2[1:, :2]

array([[4, 5]])

In [ ]:
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
dim3[1][1][2]

12

In [ ]:
dim3[1, 1, 2]

12

In [ ]:
texto = np.array(['cero', 'uno', 'uno', 'cero', 'cero', 'uno'])
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

In [ ]:
texto == 'uno'

array([False,  True,  True, False, False,  True])

In [ ]:
data[texto == 'uno']

array([[ 3,  4],
       [ 5,  6],
       [11, 12]])

In [ ]:
data[texto == 'uno', :1]

array([[ 3],
       [ 5],
       [11]])

In [ ]:
data[~(texto == 'uno')]

array([[ 1,  2],
       [ 7,  8],
       [ 9, 10]])

## Transposición de arreglos

In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
np.dot(arr.T, arr)

array([[350, 380, 410, 440, 470],
       [380, 414, 448, 482, 516],
       [410, 448, 486, 524, 562],
       [440, 482, 524, 566, 608],
       [470, 516, 562, 608, 654]])

In [ ]:
arr_t = arr.T @ arr

In [ ]:
arr_t

array([[350, 380, 410, 440, 470],
       [380, 414, 448, 482, 516],
       [410, 448, 486, 524, 562],
       [440, 482, 524, 566, 608],
       [470, 516, 562, 608, 654]])

In [ ]:
arr_t > 450

array([[False, False, False, False,  True],
       [False, False, False,  True,  True],
       [False, False,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
np.where(arr_t > 450, 1, 0)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
arr_t.mean()

486.0

In [ ]:
np.mean(arr_t)

486.0

In [ ]:
arr_t.mean(axis=1)

array([410., 448., 486., 524., 562.])

In [ ]:
arr_t.mean(axis=0)


array([410., 448., 486., 524., 562.])

In [ ]:
arr_t

array([[350, 380, 410, 440, 470],
       [380, 414, 448, 482, 516],
       [410, 448, 486, 524, 562],
       [440, 482, 524, 566, 608],
       [470, 516, 562, 608, 654]])

In [ ]:
arr_t.cumsum(axis=0)

array([[ 350,  380,  410,  440,  470],
       [ 730,  794,  858,  922,  986],
       [1140, 1242, 1344, 1446, 1548],
       [1580, 1724, 1868, 2012, 2156],
       [2050, 2240, 2430, 2620, 2810]])

In [ ]:
arr_t.cumsum(axis=1)

array([[ 350,  730, 1140, 1580, 2050],
       [ 380,  794, 1242, 1724, 2240],
       [ 410,  858, 1344, 1868, 2430],
       [ 440,  922, 1446, 2012, 2620],
       [ 470,  986, 1548, 2156, 2810]])

In [ ]:
arr = np.random.standard_normal((5,3))
arr

array([[-1.30123584,  0.69664944, -0.6125937 ],
       [-0.08300393,  0.7179013 ,  0.21242968],
       [ 0.46569574, -0.95780928, -0.82179142],
       [-1.02064194,  0.30666731, -1.5081352 ],
       [ 1.21291611,  1.72777453,  0.49130692]])

In [ ]:
arr.sort()
arr

array([[-1.30123584, -0.6125937 ,  0.69664944],
       [-0.08300393,  0.21242968,  0.7179013 ],
       [-0.95780928, -0.82179142,  0.46569574],
       [-1.5081352 , -1.02064194,  0.30666731],
       [ 0.49130692,  1.21291611,  1.72777453]])

In [ ]:
arr.sort(axis=0)
arr

array([[-1.5081352 , -1.02064194,  0.30666731],
       [-1.30123584, -0.82179142,  0.46569574],
       [-0.95780928, -0.6125937 ,  0.69664944],
       [-0.08300393,  0.21242968,  0.7179013 ],
       [ 0.49130692,  1.21291611,  1.72777453]])